/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
	google()
	mavenLocal()
	maven {
		url = uri("https://jitpack.io")	
	}
	maven {
		url = uri("https://maven.google.com")
	}
	maven {
		url = uri("https://repo.maven.apache.org/maven2/")
	}
}

dependencies {
    api(libs.com.github.appium.java.client)
    api(libs.org.seleniumhq.selenium.selenium.java)
    api(libs.org.seleniumhq.selenium.selenium.api)
    api(libs.org.seleniumhq.selenium.selenium.remote.driver)
    api(libs.com.google.android.android)
    api(libs.com.harium.android.core)
    api(libs.com.android.support.test.uiautomator.uiautomator.v18)
    testImplementation(libs.org.testng.testng)
	implementation("com.android.support.test.uiautomator:uiautomator-v18:2.1.3")
	androidTestImplementation("androidx.test.uiautomator:uiautomator:2.3.0-beta01")
}

group = "com.appium.demo"
version = "0.0.1-SNAPSHOT"
description = "AppiumDemoProject"
java.sourceCompatibility = JavaVersion.VERSION_11


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG()
}
